### ISSUE TITLE
Property 'customImage' not found on object of type 'WCLShineButton *'

### ISSUE THREAD

**Issue by atishoo** [prscX/react-native-shine-button#10]
![image](https://user-images.githubusercontent.com/7723403/41505864-68cf1332-7244-11e8-9e63-c618e8d3f2f7.png)

I have link the library, but it still not work!

RN version 0.55,Xcode v9.4

love this component so much !

but i have to remove it~ i can not solve this issue on my own

**Comment by prscX** [comment]
Thanks @atishoo for raising the issue.

Have to run `pod install` command as per README guidelines?

Thanks
</ Pranav >

**Comment by atishoo** [comment]
@prscX of course,step by step, follow guidelines

**Comment by prscX** [comment]
Hi @atishoo: Have you recently upgraded the library or this is first time you are installing the library? 

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @atishoo, Looks like the library is referring to old version of native library. Can you please try by deleting xcode Derived Data and build your project again.

Let me know in case it does not work.

Thanks
</ Pranav >

**Comment by prscX** [comment]
@atishoo: I have also encountered similar issue and post deleting Derived Data app started working as expected.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @atishoo: Hope the issue was resolved for you.

Thanks
</ Pranav >

**Comment by atishoo** [comment]
@prscX yes, the issue has been resolved. solution is delete the xcode derived data folder,thank you very much!

**Comment by prscX** [comment]
Thanks @atishoo for the update.

Thanks
</ Pranav >
