### ISSUE TITLE
IOS custom Icon is not working.

### ISSUE THREAD

**Issue by theskiesmore** [prscX/react-native-shine-button#11]
Hello, Thanks for the nice component.

Material Community Icons works well Android but IOS is not.
I think because of the font name system on IOS. 

In my case, the font filename is "materialcommunityicons.ttf" but the actual name is "Material Design Icons". 

So I modified RNVectorHelper class at RNVectorHelper.js file. 
And finally, it worked.

```
62: case "Material-Design-Icons":   // Added this line.
63: case "MaterialCommunityIcons":
```

After that, I changed my code to work on both platform Android and IOS.

thanks.

**Comment by leksyib** [comment]
@prscX  I think react-native-vector-icons needs to be updated
