### ISSUE TITLE
Could not find method google() for arguments [] on repository container.

### ISSUE THREAD

**Issue by adirzoari** [prscX/react-native-shine-button#14]
after install plugin I get this error
 > Could not find method google() for arguments [] on repository container.

my build.gradle android

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
                google()
        maven { url "https://jitpack.io" }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
                google()

        maven {
                   url "https://jitpack.io"

            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

```

**Comment by prscX** [comment]
Thanks @adirzoari for raising the issue. 

Basically `google()` is support on a specific `gradle` and `android` version. For can you please change below line in `react-native-shine-button/android/build.gradle`

`google()` -> `maven { url "https://maven.google.com" }`

I will be pushing a release with the fix. For now please use above solution.

Thanks
</ Pranav >

**Comment by adirzoari** [comment]
Hey prscx,
it still not working,
that's my update build.gradle

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
            maven { url "https://maven.google.com" 
        maven { url "https://jitpack.io" }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
             maven { url "https://maven.google.com" 

        maven {
                   url "https://jitpack.io"

            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
`

I get same error.

**Comment by prscX** [comment]
Hi @adirzoari: Same change you need to do in library `build.gradle` as well.

Let me know incase it does not work.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @adirzoari: I have a release with the fix. Can you please upgrade the library to latest version.

Please let me know incase you still face the same issue.

[V0.0.12](https://github.com/prscX/react-native-shine-button/releases/tag/v0.0.12) 

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @adirzoari: Hope the issue was resolved using the latest version.

Can I please close the issue, if it was resolved.

Thanks
</ Pranav >
