### ISSUE TITLE
SWIFT_VERSION

### ISSUE THREAD

**Issue by fjsun123** [prscX/react-native-shine-button#21]
- `WCLShineButton` does not specify a Swift version and none of the targets (`RNShineButton`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by abdelle7** [comment]
Fixed by creating an empty swift file in the project.
https://github.com/kiwi-bop/flutter_crashlytics/issues/22#issuecomment-428724123

**Comment by prscX** [comment]
@fjsun123: I have fixed and pushed the release. Thanks for raising the issue.

Thanks
< /Pranav >
