### ISSUE TITLE
Loading state?

### ISSUE THREAD

**Issue by Noitidart** [prscX/react-native-shine-button#5]
I was trying to get this to bounce around in the middle state, while my action is "loading", is it possible to get this ability without much work? An awesome awesome thansk for the immense open source work you provide the community with!!

**Comment by prscX** [comment]
Thanks @Noitidart for raising the query.

As per I can understand your query basically you are looking for a bounce state when animation is loading? If so I guess it is already supported, please find below screenshot of the same:

- **Android**

![android](https://user-images.githubusercontent.com/28862892/38163294-6fe25c14-350f-11e8-892b-a22f81026f8b.gif)

- **iOS**

![ios](https://user-images.githubusercontent.com/28862892/38163298-7541066a-350f-11e8-8306-9ddac6596ac3.gif)

Please let me know in case your expectations are something different.

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
Thanks very much for your reply!

I was thinking of something like this:


    <RNShineButton shape={"heart"} loading={true} />

I was hoping while loading is true, it is shrinking and growing, or something. Then when loading is done, I set `value={true}` which makes it shine/sparkle indicating its done.

Its like a state betweteen `value={true}` and `value={false}` while fetch request is pending.

**Comment by prscX** [comment]
@Noitidart: Got your point. As per native libraries API, I really doubt that this will be possible since their are no hooks available.

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
Oh no problem. I understand. Thank you so much for bearing with my questions and leaving topic open for me to close! :)
