### ISSUE TITLE
Trigger animation programmatically

### ISSUE THREAD

**Issue by rooque** [prscX/react-native-shine-button#9]
Is there a way?

**Comment by rooque** [comment]
When I change value prop from false to true in my state, the button change color but animation is not triggered.

**Comment by Alijaaan** [comment]
Its really important,Is there any solution to trigger the animation ?

**Comment by prscX** [comment]
Thanks @rooque + @Alijaaan for raising the query.

In my opinion animations are meant for user interaction. We do have support for showing enabled shine button. Please find below my thoughts on the same:

- Consider we have a list and each row contains a fav button. Now while showing list if shine button value is true then it will show animation on all shine buttons which will look bad.
- Even if we able animation programatically then onChange event will also be triggered, which will create future conflicts.

- I have tried requested enhancement and it was looking wired.

Please feel free to share your thoughts.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @rooque + @Alijaaan,

Can I please close this issue, since nothing much can be done in order to enable animation programmatically. 

Thanks
</ Pranav >
